<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_LoadCell" Id="{4dc582d4-e063-44b6-9e44-474d705e88f5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LoadCell EXTENDS FB_SolidSamplingModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>