<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Robot" Id="{0554418f-bec8-43af-97bb-406df361b39b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Robot
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RSR1" Id="{48966531-33d7-40db-9302-bba9452c9bd2}">
      <Declaration><![CDATA[METHOD RSR1 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="RSR2" Id="{ac5a31e9-fda5-4a1f-a31a-def60ce2e6e5}">
      <Declaration><![CDATA[METHOD RSR2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>